Repository HICC-REBOOT/HICC-REBOOT-Backend, pull requests merged in 2024-02, with the labels that each got.

#107 feat: footer 개발 (#101)
  hicc-reboot/src/main/java/hiccreboot/backend/controller/MainController.java
  hicc-reboot/src/main/java/hiccreboot/backend/dto/response/FooterResponse.java
  hicc-reboot/src/main/java/hiccreboot/backend/repository/member/MemberRepository.java
  hicc-reboot/src/main/java/hiccreboot/backend/service/MainService.java
Labels: feature

#106 refactor: 내 작성글, 댓글 정렬 순서 변경 (#100)
  hicc-reboot/src/main/java/hiccreboot/backend/service/MemberService.java
Labels: refactor

#110 feat: 일별 스케쥴 반환 기능 추가
  hicc-reboot/src/main/java/hiccreboot/backend/common/dto/Calendar/ScheduleDateResponse.java
  hicc-reboot/src/main/java/hiccreboot/backend/controller/CalendarController.java
  hicc-reboot/src/main/java/hiccreboot/backend/repository/Calender/ScheduleDateRepository.java
  hicc-reboot/src/main/java/hiccreboot/backend/service/CalendarService.java
Labels: feature

#108 feat: 회원 탈퇴시 aritlce, comment 변경
  hicc-reboot/src/main/java/hiccreboot/backend/common/consts/MemberConstants.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/dto/Article/ArticleImageResponse.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/dto/Article/ArticleListResponse.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/dto/Article/ArticleResponse.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/dto/Comment/ChildCommentResponse.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/dto/Comment/ParentCommentResponse.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/dto/Main/LatestNewsResponse.java
  hicc-reboot/src/main/java/hiccreboot/backend/domain/Article.java
  hicc-reboot/src/main/java/hiccreboot/backend/domain/Comment.java
  hicc-reboot/src/main/java/hiccreboot/backend/domain/CommentGrade.java
  hicc-reboot/src/main/java/hiccreboot/backend/domain/Department.java
  hicc-reboot/src/main/java/hiccreboot/backend/domain/Member.java
  hicc-reboot/src/main/java/hiccreboot/backend/repository/Article/ArticleRepository.java
  hicc-reboot/src/main/java/hiccreboot/backend/repository/Comment/CommentRepository.java
  hicc-reboot/src/main/java/hiccreboot/backend/service/ArticleService.java
  hicc-reboot/src/main/java/hiccreboot/backend/service/CommentService.java
  hicc-reboot/src/main/java/hiccreboot/backend/service/MemberService.java
Labels: feature

#115 feat: 내 정보 조회 기능 반환 객체 email 필드 추가 (#111)
  hicc-reboot/src/main/java/hiccreboot/backend/dto/response/ProfileMemberResponse.java
Labels: feature

#120 feat: 회원 등급을 회장으로 수정 시 회장 위임 (#119)
  hicc-reboot/src/main/java/hiccreboot/backend/service/MemberService.java
Labels: feature

#125 fix: CORS 설정 및 preflight 요청 처리 (#124)
  hicc-reboot/src/main/java/hiccreboot/backend/common/auth/config/WebSecurityConfig.java
Labels: bug

#123 fix: 회원 리스트 학과 이름 오름차순으로 정렬 (#122)
  hicc-reboot/src/main/java/hiccreboot/backend/service/MemberService.java
Labels: bug

#127 feat: 일자별 일자에 시작 시간, 끝 시간 추가 (#126)
  hicc-reboot/src/main/java/hiccreboot/backend/common/dto/Calendar/ScheduleDateResponse.java
Labels: feature

#129 feature: 비밀번호 변경 요청 시 예외 추가 (#121)
  hicc-reboot/src/main/java/hiccreboot/backend/common/exception/EmailMismatchException.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/exception/GlobalErrorCode.java
  hicc-reboot/src/main/java/hiccreboot/backend/service/EmailService.java
  hicc-reboot/src/main/resources/templates/index.html
Labels: feature

#135 feature: Redis 엔티티 자동 삭제 (#134)
  hicc-reboot/src/main/java/hiccreboot/backend/common/conf/RedisConfig.java
  hicc-reboot/src/main/java/hiccreboot/backend/service/EmailService.java
Labels: feature

#139 refactor: 설정 파일 프로퍼티화
  hicc-reboot/src/main/java/hiccreboot/backend/common/auth/config/WebSecurityConfig.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/auth/jwt/TokenProviderImpl.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/conf/CorsConfig.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/conf/EmailConfig.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/conf/PropertiesConfig.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/conf/RedisConfig.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/mail/service/EmailService.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/properties/CorsProperties.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/properties/EmailProperties.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/properties/JwtProperties.java
Labels: refactor

#143 fix: 의존성 중복 제거, 시작 시간으로 일정 조회 정렬 적용
  hicc-reboot/src/main/java/hiccreboot/backend/common/auth/config/WebSecurityConfig.java
  hicc-reboot/src/main/java/hiccreboot/backend/domains/calendar/service/CalendarService.java
Labels: bug

#146 fix: 회원 수 조회 기능 수정
  hicc-reboot/src/main/java/hiccreboot/backend/domains/main/service/MainService.java
  hicc-reboot/src/main/java/hiccreboot/backend/domains/member/repository/MemberRepository.java
Labels: bug

#147 fix: 회원 가입 시 이름 정규식 수정
  hicc-reboot/src/main/java/hiccreboot/backend/domains/auth/dto/request/SignUpRequest.java
Labels: bug

#148 feature: RequestBody에 대한 validation 적용 (#117)
  hicc-reboot/src/main/java/hiccreboot/backend/common/exception/GlobalErrorCode.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/exception/GlobalExceptionHandler.java
  hicc-reboot/src/main/java/hiccreboot/backend/common/exception/dto/ErrorResponse.java
  hicc-reboot/src/main/java/hiccreboot/backend/domains/article/controller/ArticleController.java
  hicc-reboot/src/main/java/hiccreboot/backend/domains/article/dto/request/ArticleImageRequest.java
  hicc-reboot/src/main/java/hiccreboot/backend/domains/article/dto/request/ArticleRequest.java
  hicc-reboot/src/main/java/hiccreboot/backend/domains/calendar/controller/CalendarController.java
  hicc-reboot/src/main/java/hiccreboot/backend/domains/calendar/dto/request/PostScheduleRequest.java
  hicc-reboot/src/main/java/hiccreboot/backend/domains/comment/controller/CommentController.java
  hicc-reboot/src/main/java/hiccreboot/backend/domains/comment/dto/request/PostCommentRequest.java
  hicc-reboot/src/main/java/hiccreboot/backend/domains/image/controller/S3Controller.java
  hicc-reboot/src/main/java/hiccreboot/backend/domains/image/dto/request/SimpleImageRequest.java
Labels: feature

#150 docs: README 초안 작성
  README.md
Labels: docs
